[default]
value = 1

[numerical_data_transformations]
feature_engineering.include = false

imputation.include = true
imputation.module = 'SimpleImputer'

standardisation.include = false

normalization.include = false

[categorical_data_transformations]
imputation.include = true
imputation.module = 'SimpleImputer'

one_hot_encoding.include = true
one_hot_encoding.module = 'OneHotEncoder'

